### ISSUE TITLE
Add a tiny figlet font parser

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#1]
Once a parser is written, this can be used to render the name of the CLI application in a nice way, e.g.:

```
 ______ _____  _____      _______        _____
  ____/   |   |     | ___ |       |        |  
 /_____ __|__ |_____|     |_____  |_____ __|__                                              
```

Example [here](https://github.com/rsimp/jfig/tree/master/src/main/java/io/rsimp/jfig) and some discussion on format [here](https://github.com/Marak/asciimo/issues/3).

**Comment by jdegoes** [comment]
The figlet parser should parse the figlet file format. There exist Figlet parsers in Java that could serve as inspiration.

**Comment by domartynov** [comment]
I'd like to take the ticket -- a good coding exercise for me (as a Scala noob) with a very limited in scope :)

I don't understand how the work shared between #1 and #35 -- implementing `FigDriver` covers parsing and rendering, or #35 means integration into `zio-cli`?

**Comment by FrancisToth** [comment]
Hey @domartynov , want some help on this? Let's meet on the discord channel

**Comment by jdegoes** [comment]
@domartynov This one would cover parsing, but not rendering the font. Of course, you can do parsing and rendering both!

Typically, you would parse into a typed, immutable data structure, say, `FigletFont`. Then you would have a way to render some text given a provided `FigletFont`. Hence, 2 tickets, although of course closely related.

**Comment by domartynov** [comment]
That's the plan. The referenced Java implementation incapsulates all in FIGEngine (in OOP manner), so i initially assumed that in the context of `zio-cli` we just want to expose only something like `Figlet.render(flfPath:String, text: String): String` as the use case is narrow :)

**Comment by jdegoes** [comment]
@domartynov Good luck! WIth @FrancisToth's help you're in good hands. 😉
