### ISSUE TITLE
Flatten Units in `++`, `.subcommands`, and `Command.apply` methods

### ISSUE THREAD

**Issue by kitlangton** [zio/zio-cli#103]
This will be similar to ZIO's `Zippable`, which helps deal with awkward nesting of tuples when zipping polymorphic effects. In our case, don't want to be forced to `.map(_._2)`, when the left or right hand side of a composed Command/Options/Args is a Unit. These Units are usually the cruft of combining Options or Args values that do not generate a value. For example:

`Command("something", Options.none, Args.int)` will generate a `Command[(Unit, Int)]`. Though, with this new capability, it should return `Command[Int]`.

I'd recommend taking a look at the implementation of `Zippable` as well as the Zymposium on Path Dependent Types.

**Comment by kitlangton** [comment]
Happy to do this as a giant pairing session if anyone is interested :)

**Comment by jdegoes** [comment]
🙏 🙏 🙏 

"Composable zips"

**Comment by NavidJalali** [comment]
I will try this out
