### ISSUE TITLE
Improve Command.apply to not require Options.none/Args.none

### ISSUE THREAD

**Issue by kitlangton** [zio/zio-cli#104]
If we can make Options.none and Args.none extend Option[Nothing]/Args[Nothing], then we'll be able to provide default values for these in the `Command.apply` method. Currently, you need to write Args.none or Options.none, which isn't as nice as it could be.

**Comment by jdegoes** [comment]
I am not sure if this will work, but if it has issues, I would recommend that you add `.args` and `.options` methods on `Command`, which zip together the existing args/options with the provided (new) args/options. Then the constructor for `Command` can just take a string, and you can do `Command("foo").args(...).options(...)`. The `Unit` will go away through compositional zips.
