### ISSUE TITLE
Display subcommands in HelpDoc synopsis

### ISSUE THREAD

**Issue by justin-corn** [zio/zio-cli#112]
When using subcommands, the generated synopsis for non-leaf subcommands does not include the partial subcommand "path."

For example, given a sub command structure
```
foo
└── a
    └── one
        ├── blue
        └── red
```
such that `foo a one blue` is a leaf command, the `Synopsis` section in `--help` documentation doesn't include relevant subcommand names.

Example:
Any level of non-leaf subcommand  `foo a --help`, `foo a one --help`, produces
```
SYNOPSIS

    foo   <command> [<args>]
```

The expected output for `foo a --help` would be
```
SYNOPSIS

    foo a <command> [<args>]
```

and for `foo a one --help`
```
SYNOPSIS

    foo a one <command> [<args>]
```

and for `foo a one blue --help`
```
SYNOPSIS

    foo a one blue [<args>]
```

Note that the expected synopsis for a leaf command does _not_ include the string `<command>` (whereas it is included in the current code), but that can be considered a separate issue.

## Bonus nitpick
There's an extra space in here :)
```
SYNOPSIS

    foo   <command> [<args>]
       ^^^
```

**Comment by jorge-vasquez-2301** [comment]
I'm working on this one 🙂

**Comment by jdegoes** [comment]
@jorge-vasquez-2301 Is this one done??
