### ISSUE TITLE
Display possible subcommands for non-leaf nested subcommands

### ISSUE THREAD

**Issue by justin-corn** [zio/zio-cli#113]
When using nested subcommands, the generated help doc does not list subcommands for any non-leaf subcommand whose distance from a leaf is > 1.

For example, given a sub command structure
```
foo
└── a
    └── one
        ├── blue
        └── red
```
The this command correctly enumerates subcommands in the `SUBCOMMANDS` section in the help doc
```
foo a one --help
```
But these commands do not
```
foo --help
```
```
foo a --help
```

**Comment by dbuschman7** [comment]
I just ran into this.

**Comment by abcpro1** [comment]
Can you show how a desired output should look like?
