### ISSUE TITLE
Replace Reducable with Zippable?

### ISSUE THREAD

**Issue by DamianReeves** [zio/zio-cli#123]
It seems to me that `zio-cli`'s `Reducable` can now be replaced by `Zippable` from `zio` now that we are on `ZIO` 2.0.

What do you think? Can we drop `Reducable` and just use `Zippable`?

@jdegoes , @kitlangton , @adamgfraser

**Comment by jdegoes** [comment]
It looks to me like that's the case.

**Comment by kitlangton** [comment]
Oops. I commented on the discord, but will copy here:

There's a slight semantic difference. Recudable—which is a bad name :D—simply removes units when zipping, but keeps other tuples. I found this to be slightly nicer in the instances we're using it here.
