### ISSUE TITLE
Add parsers / validators for PrimType

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#20]
All the PrimType methods need a validator / parser. The method has been sketched out but not implemented.

**Comment by edvmorango** [comment]
Hi John, I've started to work on that issue, but I had troubles with the Scala compiler (something related to the GADT), I've tried these snippets: 

```
sealed trait PrimType[+A] { self =>
  def validate(value: String): IO[String, A] = self match {
  case Text => ZIO.succeed(value)
  }
}

/*
PrimType.scala:31:10: pattern type is incompatible with expected type;
[error] found : zio.cli.PrimType.Text.type
[error] required: zio.cli.PrimType[A]
[error] case Text => ZIO.succeed(value)

PrimType.scala:31:30: type mismatch;
[error] found : value.type (with underlying type String)
[error] required: A
[error] case Text => ZIO.succeed(value)
*/
```

```
sealed trait PrimType[+A] { self =>
  def validate(value: String): IO[String, A] = self match {
  case _: PrimType[String] => ZIO.succeed(value)
  }
}
/*
PrimType.scala:31:45: type mismatch;
[error] found : value.type (with underlying type String)
[error] required: A
[error] case _: PrimType[String] => ZIO.succeed(value)
[info] value.type <: A?
*/
```

Could you help me?

**Comment by jdegoes** [comment]
@edvmorango Try to just implement the method in each subtype and see if that solves the problem.

It may be caused by the covariance on `A` which could be solved by implementing it privately in the companion object and delegating to that implementation in the supertype.

**Comment by defrag** [comment]
Hey folks, my bad that i didn't check issue this morning, didn't see anyone started working on it, and i flushed some first version in #21 .
