### ISSUE TITLE
Allow chaning type name

### ISSUE THREAD

**Issue by senia-psm** [zio/zio-cli#238]
At the moment there is no way to change type name.

This help is not really descriptive: `$ test -i text`.  If you have multiple options you have multiple `-a text -b text -c text` and this `text` means nothing, especially if you are using `mapOrFail` to validate this text.

It would be much more descriptive with ability to customise this type name, i.e.:   `$ test -i <id> -n <name> -u <uuid>`

**Comment by pablf** [comment]
In this case, it might be better to use a full name and an alias and make configurable the appearance of the type. It would appear when asking for more detailed help.

**Comment by senia-psm** [comment]
Even with full name custom string instead of `text` would be more informative.
