### ISSUE TITLE
v0.5 mislabeled as v0.6 in README/Github?

### ISSUE THREAD

**Issue by oschrenk** [zio/zio-cli#247]
The README states

> libraryDependencies += "dev.zio" %% "zio-cli" % "0.6.0"

and the Github release also states that 0.6.0 is released

I can't find the version online 

```
cs fetch dev.zio::zio-cli:0.6.0
Exception in thread "main" coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for dev.zio::zio-cli:0.6.0 (likely a non existing module or version)
```

while

```
cs fetch dev.zio::zio-cli:0.5.0
~/.../Coursier/v1/https/repo1.maven.org/maven2/dev/zio/zio-cli_3/0.5.0/zio-cli_3-0.5.0.jar
```

works fine

Looking at 

https://repo1.maven.org/maven2/dev/zio/zio-cli_2.13/

the latest release is `0.5.0` and the release date of 0.5.0 in Maven is the same as the 0.6.0 in Github

So 0.5.0 is the latest, I presume?

**Comment by vigoo** [comment]
0.5.0 is the latest
