### ISSUE TITLE
Variadic Args.file with exists=true fails with wrong error message if file does not exist

### ISSUE THREAD

**Issue by TobiasPfeifer** [zio/zio-cli#33]
`(Args.file("files", true) *).validate("doesNotExist.file" :: Nil, ParserOptions.default)`

fails with

`List(Paragraph(Error(Text(Unexpected arguments for command wc: List(doesNotExist.file)))))`

expected

`List(Paragraph(Error(Text(doesNotExist.file is not a recognized path.))))`

Can be reproduced by running the `WcApp` Example with unrecognized file.

My investigation so far:

`validate` in `Variadic` turns a validation failure into a success without consuming the argument. The unconsumed argument leads to "Unexpected arguments..."

**Comment by Mohamedali10** [comment]
@jdegoes I will try to work on this issue.

**Comment by TobiasPfeifer** [comment]
@Mohamedali10 where you able to reproduce the bug? I've just recognized the changes introduced to fix #40 could also have fixed this already

**Comment by Mohamedali10** [comment]
@TobiasPfeifer using the repeat method could reproduce the problem, but it can not reproduce the problem if we use repeat1 that comes from the fix #40 .
