### ISSUE TITLE
Add a figlet font renderer

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#35]
This can be used to render the name of the CLI application in a nice way, e.g.:

```
 ______ _____  _____      _______        _____
  ____/   |   |     | ___ |       |        |  
 /_____ __|__ |_____|     |_____  |_____ __|__                                              
```

Example [here](https://github.com/rsimp/jfig/tree/master/src/main/java/io/rsimp/jfig) and some discussion on format [here](https://github.com/Marak/asciimo/issues/3).

This will be used in conjunction with #1.

**Comment by FrancisToth** [comment]
Working on this :)

**Comment by jdegoes** [comment]
@FrancisToth Awesome! Should be both tricky and fun in the way these sorts of problems tend to be. 😄
