### ISSUE TITLE
Implement `HelpDoc.toHTML`

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#38]
Currently, `HelpDoc.toPlaintext` is implemented. However, some details are not preserved well in plaintext format, but can be captured more precisely using HTML. Therefore, we should implement a renderer to HTML on `HelpDoc`, which tries to create a beautiful and useful representation of the help documentation for a CLI application.

**Comment by FrancisToth** [comment]
I can give a try on this one :)

**Comment by FrancisToth** [comment]
So far I've implemented a very simple rendered that renders the `zio.cli.CommandSpec.Tail` like this:
```
<html><head></head><body><h1>arguments</h1><br/>&lt;file&gt;<p>A user defined piece of text.</p><br/><h1>options</h1><br/>--n<p>An integer.</p></body></html>
```
This is far from being beautiful. Should I simply add some CSS to make it nicer? Or would this be the goal of another issue?

**Comment by jdegoes** [comment]
I think some CSS to make it look nice by default would be quite nice!

**Comment by FrancisToth** [comment]
I'm not really a good web developer, but I took some inspiration from ZIO's website. I'd like to extract the hardcored CSS code and use an external file instead, but this would imply returning an effect from `toHtml`. Maybe more work would be required here, but I'd like some feedback first. I hope it meets your expectations :)

https://github.com/zio/zio-cli/pull/61
