### ISSUE TITLE
Smoothly integrate built-in commands into user's own `Command` structure

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#39]
The user of ZIO CLI must define a CLIApp, which is the command-line application itself. One of the fields is `Command`, which represents the top-level command of the CLI application.

Currently, this command is kept separate from the "built-in" options that CLIApp supports, including `--help`, and in the future, `--version`. This means that when a user prints out help documentation, the `--help` option is not included in the help documentation.

In order to avoid this problem, we need to push the help option and other options into the user's own command structure. Probably, this can be done by adding a new method to `Command`, such as:

```scala
sealed trait Command[A] {
  ...
  def addOption[B](opt: Options[B]): Command[Either[B, A]]
  ...
}
```

Then with this new method, the `--help` option that CLIApp provides "for free" can be cleanly integrated into the existing user's Command, so that when `--help` is run, that option appears with other documented help options.

**Comment by Bloznelis** [comment]
I would like to work on this one during the hackathon.

**Comment by jdegoes** [comment]
@Bloznelis Sounds good. Warning: This one is quite tricky! Let me know if you want a hand or need a backup (/simpler) ticket.
