### ISSUE TITLE
Document and verify / add tests for all Options constructors

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#41]
The Options constructors create a wide range of options. Their `validate` method and other methods should be documented and tested in `OptionsSpec`.

**Comment by kovszilard** [comment]
I would like to work on this.

**Comment by jdegoes** [comment]
@kovszilard Sounds great! You can see some Options already have a few tests, but mostly, the file `Options.scala` is untested. So you could systematically work through the constructors and operators, and add more tests to the existing Spec. Let me know if you have any questions!

**Comment by jdegoes** [comment]
@kovszilard Did we get this merged in?
