### ISSUE TITLE
Document and verify / add tests for all Args constructors

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#42]
The Args constructors create a wide range of options. Their validate method and other methods should be documented and tested in ArgsSpec.

**Comment by shankarshastri** [comment]
@jdegoes , I would like to explore this.

**Comment by jdegoes** [comment]
@shankarshastri Sounds great! The `ArgsSpec` already exists in the `test` directory and has a few basic tests, so the idea is to just expand them and be sure to test everything in the `Args.scala` file. Let me know if you have any questions!

**Comment by shankarshastri** [comment]
@jdegoes , It will be great if you can point me to the file, because I couldn't find it

**Comment by shankarshastri** [comment]
@jdegoes , I was starting on it, should we test the method wise for each class that extends Args?

**Comment by shankarshastri** [comment]
I understood that PrimeTypeSpec.scala already has tests covered, except for few cases which needs to be covered. I will take a look at them :)
