### ISSUE TITLE
Ensure tests are run using Github Actions

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#46]
Would be nice to integrate with Github Actions to run tests on pull requests and merges to master.

Any volunteers? 😄

**Comment by katlasik** [comment]
I can work on this one

**Comment by jdegoes** [comment]
@katlasik Great, let me know if you have any questions!

**Comment by katlasik** [comment]
@jdegoes I created [PR](https://github.com/zio/zio-cli/pull/49). 

I run tests on java 8, 11 and 14. Is that ok?

I don't know Scala.js very well, do we also need to run specific tests for it?
