### ISSUE TITLE
Extract out examples into a separate top-level "examples" project, and add more details

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#48]
Currently thanks to @TobiasPfeifer and @ashprakasan, we have some examples of ZIO CLI in the `Example.scala`.

However, we should extract these examples into a separate top-level project, make sure each of them is in a separate file, and try to more fully flesh them out or add other examples that demonstrate more of ZIO CLI's features for options and arguments.

**Comment by asakaev** [comment]
I will take it with @vladimir-popov @sapizhak

**Comment by TobiasPfeifer** [comment]
I've already implemented WcApp using ZStream to print file statistics for #12 this morning
I'll rebase my changes on top of @asakaev changes #50 
@vladimir-popov @sapizhak have you already put work into implementing logic for WcApp?

**Comment by vladimir-popov** [comment]
we've already done all what we wanted in this PR
