### ISSUE TITLE
Implement error-correction using Levenshtein distance

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#5]
If a command or flag is not recognized verbatim, then using Levenstein distance calculation, the closest command(s) / flag(s) can be identified, and the suggestion made to the user.

e.g.:

```
> myapp load -forc -source foo.txt

- The flag "-forc" is not recognized. Did you mean "-force"?
```

In order to implement this feature, a simple Levenstein distance function can be implemented. Atop this, a separate method can be added to `Command`, perhaps, `autoCorrections`, which returns a `List[HelpDoc]` containing any possible auto-corrections.

Then, inside `CLIApp`, if it is not possible to parse the command-line arguments, then auto-corrections can be generated.

**Comment by eriktim** [comment]
I would like to work on this one.

**Comment by a-morales** [comment]
Hello, I'd like to help with this task.

**Comment by jdegoes** [comment]
@a-morales Awesome! You might use Discord to find someone to help pair on this, or feel free to reach out to me for clarifications or help!

This could be divided into two phases:

1. Implementing Levenstein distance, together with tests, using memoization + recursion, or dynamic programming. There are lots of existing implementations in the wild to draw inspiration from.
2. Using this distance function to produce auto-completions. Although I initially proposed adding a method to `Command`, I now think that when parsing fails, the failure messages themselves could contain the auto-corrections. This might generate better auto-corrections, because it can help localize the auto-corrections to the correct command / subcommand.

Let me know if you need any help!
