### ISSUE TITLE
Implement parser for CLI

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#8]
We need to parse the command-line options into the data type required by the user.

**Comment by DamianReeves** [comment]
I'll give this one a shot.

**Comment by DamianReeves** [comment]
So is parsing just directly matching the datatype assuming we've already "mapped" sections of the command line to portions of the command line?
 
Or is it more validating the command-line against a "schema"?
Do we build up the Schema like a parser combinator would for example, from the ADT we've provided?

**Comment by jdegoes** [comment]
@DamianReeves 

The core parsing functionality we need to implement is sketched out in `Command#validate`, which currently has this  sig:

```scala
final def validate(args: List[String], opts: ParserOptions): IO[List[HelpDoc.Block], (List[String], A, B)] = ???
```

At a high-level, this function either:

1. Fails, in which case it fails with one or more `HelpDoc.Block` messages./
2. Succeeds, in which case it produces a tuple containing:
  - Remaining command line arguments
  - Options
  - Consumed Arguments

A command is responsible for pulling off all the arguments and the options that it requires (but no more!!). Leaving the rest to be processed by subcommands (but this will *not* happen in `validate`, that will be driven at a higher-level).

Now I haven't written any of this so I could be wrong on details, so YMMV.

**Comment by jdegoes** [comment]
Fixed enough for now, modulo bugs and improvements.
