### ISSUE TITLE
Ensure subcommands parse their command-names from the command-line arguments

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#84]
We need a test case that when we have something like `git merge` (a top-level command `git` with a subcommand `merge`), that the subcommand parses off the subcommand name (`merge`) from the command-line arguments, before trying to parse its own options and args.

**Comment by landlockedsurfer** [comment]
I already made some progress on this... pull request will hopefully come soon.

**Comment by jdegoes** [comment]
Awesome!
